name: Update public Postman collection

on:
  push:
    branches: [ main ]

env:
  COLLECTION_ID: ${{ vars.COLLECTION_ID }}
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

jobs:
  update_public_collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prepare collection to send
        run: |
          echo "{\"collection\": $(cat postman/collections/WebhooksPayloads.json)}" > /tmp/WebhooksPayloads.json

      - name: Update the collection
        run: |
          collection_id="${{ env.COLLECTION_ID }}"
          api_key="${{ env.POSTMAN_API_KEY }}"
          curl --fail --location --request PUT \
            "https://api.getpostman.com/collections/$collection_id" \
            -H "X-Api-Key: $api_key" \
            -H 'Content-Type: application/json' \
            --data @/tmp/WebhooksPayloads.json
