name: Update developer portal (v2)

on:
  push:
    branches: [ main ]
    paths:
      - 'openapi.json'
      - '.github/workflows/update-developer-portal.yml'

jobs:
  update_developer_portal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: readmeio/rdme@v8
        with:
          rdme: openapi ./openapi.json --key=${{ secrets.README_API_KEY }} --id=6750962581a60000537e1d79 --version=v2